### ISSUE TITLE
Env vars should match flags

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/cli-old#198]
`OXIDE_ORG` vs `--organization`

Came up while Bryan was doing a Friday runthrough.

**Comment by plotnick** [comment]
Should also add `OXIDE_PROJECT` env var.

**Comment by karencfv** [comment]
Definitely agree on this one. Thanks for opening up an issue!

**Comment by karencfv** [comment]
I've been thinking about the `OXIDE_PROJECT` env var. I believe excluding this variable may have been by design. Customers will likely be jumping from project to project more often than organization, which you'll likely stick to one for most of the time.

Also, having clarity on which project you performed and action on your bash history will be really helpful during incidents.

I think I'll change the `OXIDE_ORG` env var after the demo dry run just to make sure I don't break anything 😅

**Comment by karencfv** [comment]
Superseded by work on new CLI
