### ISSUE TITLE
need support for silos and IdPs

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/cli-old#219]
As an example, we want to be able to do [this](https://github.com/oxidecomputer/meta/blob/master/engineering/remote-access-preview-demo-setup.adoc#setting-up-a-new-silo-with-saml-authentication) with the CLI:

```
$ oxide api /silos --method POST

$ oxide api /silos/pluto/saml_identity_providers --method POST
```

(specific input examples are in that link)
CC @jmpesp

**Comment by karencfv** [comment]
Thanks for opening up this issue! Just a question, is this absolutely necessary for the demo? Otherwise I'd like to keep it on the backlog for a bit. This is because I'm planning to move the Rust SDK to use progenitor instead of its own custom generator, and we have this coming along -> https://github.com/oxidecomputer/omicron/pull/1329. These two things will change a lot of things and will be a bit of a major overhaul. This means I want to add as few things as possible to the CLI for the time being.

I'm writing up a plan of attack for this work, will share it with the team once it's ready!

**Comment by davepacheco** [comment]
These are one-time steps that are more akin to rack setup than they are to the rest of the demo.  So while we do plan to demo features that use this, it's probably okay to use the raw API commands since those would be happening offline before the actual demo starts.  CC @smklein

**Comment by karencfv** [comment]
Sounds great thanks!!

**Comment by karencfv** [comment]
This is being worked on a par of a larger task in https://github.com/oxidecomputer/oxide-sdk-and-cli .

Closing this issue as I will be archiving this repo :)
