### ISSUE TITLE
Would like commands to manage IP Pools

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/cli-old#220]
With the integration https://github.com/oxidecomputer/omicron/pull/1253 and https://github.com/oxidecomputer/omicron/pull/1298, we have the basic API endpoints for operating on IP pools. It would be nice to have explicit CLI commands for this.

**Comment by bnaecker** [comment]
The relevant commands are CRUD on the `/ip-pools` URI, and POST operations to `/ip-pools/{pool_name}/ranges/add` and `/ip-pools/{pool_name}/ranges/delete`. Examples:

### Adding an IP Pool

```
oxide api /ip-pools --method POST --input - <<EOF
{
  "name": "mypool",
  "description": "an IP pool"
}
EOF
```

IP Pools are named resources like most others, so also support:

- updating the name/description
- deleting
- fetching a single pool
- paginated listing of pools

### Adding a range to the above pool

```
oxide api /ip-pools/mypool/ranges/add --method POST --input - <<EOF
{
  "first": "10.0.0.1",
  "last": "10.0.0.255"
}
EOF
```

Deleting a range looks similar.

**Comment by rmustacc** [comment]
So one thing for us to call out is that POSTing and updating IP pools is an operator thing. I think it makes sense for us to have it all in one CLI, but just wanted to mention that.

**Comment by karencfv** [comment]
Thanks for opening up this issue! Just a question, is this absolutely necessary for the demo? Otherwise I'd like to keep it on the backlog for a bit. This is because I'm planning to move the Rust SDK to use progenitor instead of its own custom generator, and we have this coming along -> https://github.com/oxidecomputer/omicron/pull/1329. These two things will change a lot of things and will be a bit of a major overhaul. This means I want to add as few things as possible to the CLI for the time being.

I'm writing up a plan of attack for this work, will share it with the team once it's ready!

**Comment by bnaecker** [comment]
@karencfv I defer to you how to sequence this, just wanted to make sure we don't lose track of the work!

**Comment by karencfv** [comment]
Thanks a bunch! 🙇‍♀️

**Comment by karencfv** [comment]
These are included in the new CLI rework
